[project]
name = "spotify-exporter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dictor>=0.1.12",
    "fastapi>=0.116.1",
    "pkce>=1.0.3",
    "requests>=2.32.4",
    "ruff>=0.12.4",
]
